### ISSUE TITLE
Setup an api for CRUD operations and paste the URL here

### ISSUE THREAD

**Issue by rajkumar82** [Jothi-prakash/simple_crud_api_app#3]
Setup an api for CRUD operations and paste the URL here

**Comment by Jothi-prakash** [comment]
API URL =https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c

Post method : for adding 
------------------------------

Changes= body // adding a person details

url=https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c/users


Post method : for update a details  
------------------------------------------

Changes= body // adding a person details

url=https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c/users/63f315701d8b0e03e81412a2


Get method : for reading all persons  
--------------------------------------------

Changes = null

url=https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c/users


Get method : for reading  one person 
--------------------------------------------

Changes = null

url=https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c/users/63f315701d8b0e03e81412a2


Put method: for delete a person
-----------------------------------------

Changes =null 

url=url=https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c/users/63f315701d8b0e03e81412a2


Put method: for delete all person
-----------------------------------------

Changes =null 

url=url=https://crudcrud.com/api/5a3e20ac44dd4101a76d970738ff346c/users

**Comment by rajkumar82** [comment]
you can proceed to model creation now
